
// export let SCREENS = {
//   ONBOARDING: 'Onboarding',
//   WELCOME: 'Welcome',
//   LOGIN: 'Login',
//   SIGNUP: 'Signup',
//   PROGRESS: 'Progress',
//   VERIFYCODE: 'VerifyCode',
//   FORGET: 'Forget',
//   RESETPASSWORD: 'ResetPassword',
//   HOME: 'Home',
//   FILTERS: 'Filters',
//   MESSAGES: 'Messages',
//   BOOKING: 'Booking',
//   SEEALL: 'SeeALL',
//   DETAILS: 'Details',
//   PROFILE: 'Profile',
//   TERMSANDCONDITION: 'TermsAndCondition',
//   DASHBOARD: 'dashboard',
//   TABS: 'Tabs',
//   SEEALLDOCTORS: 'SeeAllDoctors',
//   // DOCTORDETAILS: 'DoctorDetails',
//   NEWAPPOINTMENT: 'NewAppointment',
//   NOTIFICATONS: 'Notifications',
//   CHAT: 'Chat',
//   UPDATEPROFILE: 'UpdateProfile',
//   FAVORITES: 'Favorites',
//   HELPCENTER: 'HelpCenter',
//   PAYMENTOPTION: 'PaymentOption',
//   PASSWORDMANAGER: 'PasswordManager',
//   NOTIFICATIONSETTINGS: 'NotificationsSettings',
//   THEMESETTINGS: 'ThemeSettings',
//   MYAPPOINTMENT: 'MyAppointment',
//   CANCELAPPOINTMENT: 'CancelAppointment',
//   ADDCARD: 'AddCard',
//   REVIEWSUMMARY: 'ReviewSummary',
//   PAYMENTSUCCESS: 'PaymentSuccess',
//   CALL: 'CallScreen',
//   CALL_HISTORY: 'CallHistory',

//   // Add OTP Screen constant
//   OTPSCREEN: 'OtpScreen',
//   OTP: 'OtpScreen',

//   // Doctor Module Screens
//   DOCTOR_DASHBOARD: 'DoctorDashboard',
//   DOCTOR_PROFILE: 'DoctorProfile',
//   DOCTOR_PATIENTS: 'DoctorPatients',
//   PATIENT_PROFILE: 'PatientProfile',
//   CONSULTATION_NOTES: 'ConsultationNotes',
//   MANAGE_AVAILABILITY: 'ManageAvailability',
//   DOCTOR_EARNINGS: 'DoctorEarnings',
//   DOCTOR_APPOINTMENTS: 'DoctorAppointments',

//   DOCTOR_BOTTOM_TABS: 'DoctorBottomTabs',
//   DOCTOR_ADMIN_CHAT: 'DoctorAdminChat',
//   DOCTOR_PAYMENT_OPTIONS: 'DoctorPaymentOptions',
// };
export const SCREENS = {
  ONBOARDING: 'Onboarding',
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  PROGRESS: 'Progress',
  VERIFYCODE: 'VerifyCode',
  FORGET: 'Forget',
  RESETPASSWORD: 'ResetPassword',
  HOME: 'Home',
  FILTERS: 'Filters',
  MESSAGES: 'Messages',
  BOOKING: 'Booking',
  SEEALL: 'SeeALL',
  DETAILS: 'Details',
  PROFILE: 'Profile',
  TERMSANDCONDITION: 'TermsAndCondition',
  DASHBOARD: 'dashboard',
  TABS: 'Tabs',
  SEEALLDOCTORS: 'SeeAllDoctors',
  NEWAPPOINTMENT: 'NewAppointment',
  NOTIFICATONS: 'Notifications',
  CHAT: 'Chat',
  UPDATEPROFILE: 'UpdateProfile',
  FAVORITES: 'Favorites',
  HELPCENTER: 'HelpCenter',
  PAYMENTOPTION: 'PaymentOption',
  PASSWORDMANAGER: 'PasswordManager',
  NOTIFICATIONSETTINGS: 'NotificationsSettings',
  THEMESETTINGS: 'ThemeSettings',
  MYAPPOINTMENT: 'MyAppointment',
  CANCELAPPOINTMENT: 'CancelAppointment',
  ADDCARD: 'AddCard',
  REVIEWSUMMARY: 'ReviewSummary',
  PAYMENTSUCCESS: 'PaymentSuccess',
  CALL: 'CallScreen',
  CALL_HISTORY: 'CallHistory',

  // OTP Screen constants
  OTPSCREEN: 'OtpScreen',

  // Doctor Module Screens
  DOCTOR_DASHBOARD: 'DoctorDashboard',
  DOCTOR_PROFILE: 'DoctorProfile',
  DOCTOR_PATIENTS: 'DoctorPatients',
  PATIENT_PROFILE: 'PatientProfile',
  CONSULTATION_NOTES: 'ConsultationNotes',
  MANAGE_AVAILABILITY: 'ManageAvailability',
  DOCTOR_EARNINGS: 'DoctorEarnings',
  DOCTOR_APPOINTMENTS: 'DoctorAppointments',
  DOCTOR_MESSAGES: 'DoctorMessages',
  DOCTOR_TAB_NAVIGATOR: 'DoctorTabNavigator',
  DOCTOR_BOTTOM_TABS: 'DoctorBottomTabs',
  DOCTOR_ADMIN_CHAT: 'DoctorAdminChat',
  DOCTOR_PAYMENT_OPTIONS: 'DoctorPaymentOptions',
};
